version: '3'

services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=bookstore
      - POSTGRESQL_PASSWORD=bookstore
      - POSTGRESQL_DATABASE=bookstore
      - POSTGRES_INITDB_ARGS="--encoding=utf8"
    volumes:
      - volume-postgres-master:/bitnami
volumes:
  volume-postgres-master: