spring:
  datasource:
      username: bookstore
      password: bookstore
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/bookstore
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            temp:
                use_jdbc_metadata_defaults: false
    show-sql: true
